# Generated by Django 6.0.5 on 2026-05-13 19:58

import auth_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.models.CustomUserManager()),
            ],
        ),
    ]
